---
title: "Keras Tutorials"
author: "Mike McPhee Anderson"
date: "8/18/2019"
output: html_document
---

```{r setup, include=FALSE}

if (!require("pacman")) {
  install.packages("pacman")
  library("pacman")
}

if (!require("keras")) {
  devtools::install_github("rstudio/keras")
  library("keras")
}

pacman::p_load(tidyverse, RMySQL, devtools, keras, tensorflow, gridExtra)

use_condaenv("tf")

knitr::opts_chunk$set(echo = TRUE)
```

## Load the MNist Dataset

```{r data-parition-reshape}

mnist = dataset_mnist()

x_train = mnist$train$x
y_train = mnist$train$y
x_test = mnist$test$x
y_test = mnist$test$y

# reshape
x_train = array_reshape(x_train, c(nrow(x_train), 784))
x_test = array_reshape(x_test, c(nrow(x_test), 784))

# rescale (map grayscaled values from 0-255 to 0-1)
x_train = x_train / 255
x_test = x_test / 255

y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)
  

```

## Define the model

```{r model-definition}

model = keras_model_sequential() 

model %>% 
  layer_dense(units = 256, activation = 'relu', input_shape = c(784)) %>% 
  layer_dropout(rate = 0.4) %>% 
  layer_dense(units = 128, activation = 'relu') %>%
  layer_dropout(rate = 0.3) %>%
  layer_dense(units = 10, activation = 'softmax')

summary(model)
```

## Compile Model 

* Set optimizer, metrics, and loss function

```{r model-compile}

model %>% compile(
  loss = 'categorical_crossentropy',
  optimizer = optimizer_rmsprop(),
  metrics = c('accuracy')
)

```

```{r model-train, message=FALSE}

history = model %>% fit(
  x_train, y_train, 
  epochs = 30, batch_size = 128, 
  validation_split = 0.2
)

```




```{r model-auto-encoder-basic}

encoding_dim = 16L

autoencoder = keras_model_sequential()

autoencoder %>% 
  layer_dense(encoding_dim, activation='relu', input_shape = c(784L)) %>%
  layer_dense(784L, activation='sigmoid') 

autoencoder %>% compile(
  loss = loss_binary_crossentropy,
  optimizer = optimizer_rmsprop(),
  metrics = c(metric_binary_accuracy)
)

autoencoder %>% fit(
  x_train, x_train, 
  epochs = 10, batch_size = 256, 
  shuffle = TRUE,
  validation_data=list(x_test, x_test)
)


```

```{r}

encoder = keras_model_sequential(layers=list(autoencoder$layers[[1]]  ))
encoded_img = encoder$predict(x_test)

decoder = keras_model_sequential(layers=list(autoencoder$layers[[2]]))
decoded_img = decoder$predict(encoded_img)
  

```


```{r}

par(mfcol=c(6,6))
par(mar=c(0, 0, 3, 0), xaxs='i', yaxs='i')

for (idx in 1:36) { 
    im <- x_test[idx,]
    im <- array_reshape(im, c(28,28))
    im <- t(apply(im, 2, rev))
    image(1:28, 1:28, im, col=gray((0:255)/255), 
          xaxt='n', main=paste(mnist$test$y[idx]))
}

for (idx in 1:36) { 
    im <- decoded_img[idx,]
    im <- array_reshape(im, c(28,28))
    im <- t(apply(im, 2, rev))
    image(1:28, 1:28, im, col=gray((0:255)/255), 
          xaxt='n', main=paste(mnist$test$y[idx]))
}

```


```{r fig.width=12, fig.height=10}

plot_list <- list()

for (i in 1:9) {
  curr_label <- as.character(i)
  encoder_plot_data <- cbind(as.data.frame(encoded_img), data.frame(label=mnist$test$y))
  encoder_plot_data$obs_id <- 1:nrow(encoder_plot_data)
  encoder_plot_data$plot_label <- paste(encoder_plot_data$obs_id, encoder_plot_data$label)
  
  encoder_plot_data <- encoder_plot_data %>% filter(label == curr_label)
  encoder_plot_data <- encoder_plot_data[sample(1:nrow(encoder_plot_data), 30), ]
  encoder_plot_data <- gather(encoder_plot_data, "Node", "Activation", V1:V16)
  
  
  plot_list[[i]] <- ggplot(data=encoder_plot_data, aes(x=Node, y=plot_label)) +
    geom_tile(aes(fill=Activation)) + 
    scale_fill_gradient(low = "white", high = "red") + 
    ggtitle(paste("Digit", curr_label)) + 
    theme(axis.title.x=element_blank(),
          axis.text.x=element_blank(),
          axis.ticks.x=element_blank(),
          axis.title.y=element_blank(),
          axis.text.y=element_blank(),
          axis.ticks.y=element_blank(),
          legend.position = "none")  

}

grid.arrange(grobs=plot_list, ncol=3)

```





